### ISSUE TITLE
[EPIC] Support/Vote without the need to be registered to Decidim

### ISSUE THREAD

**Issue by tramuntanal** [CodiTramuntana/decidim-verify_wo_registration#6]
## Is your feature request related to a problem? Please describe.

As a user I want to have the possibility to vote / support the proposals and the participatory budgets, without having to register to Decidim platform. 
I just want to check DNI/NIE and birthdate against the verification method and asking for the sex (Man / Women / No binary)

Must be met at:
- [ ] Proposals component: Support for Proposals
- [ ] Budget component: Vote to projects

### Configuration
Since not all organizations (tenants) will always need to be able to support/vote without being registered, this functionality may need to be activated and deactivated for each component. 
That is to say, for each component (Proposals and Budgets) that exists in each space, this functionality can be activated or not.
This will be done through a new flag on the component edit page.

### Verification system for unregistered voting guidance

Currently, impersonated users are only asked to be verified through a single verifier. This is because these participants are already previously validated by the administrator who guides them.

When voting targeting functionality is activated without registration but it is allowing participants to provide guidance independently, so you have to ask for the same guarantees that are requested from a registered user.
It would not make sense to ask for more verification to a registered user than to a user who only wants to vote, but without being registered on the platform.

### Admin
- Add boolean "Enable voting targeting system without being registered" to Proposals Component
![screenshot-localhost_3000-2019 10 21-10_04_24](https://user-images.githubusercontent.com/28536082/67187316-39417a00-f3ea-11e9-9017-9f035d1ef91f.png)
- Add boolean "Enable voting targeting system without being registered" to Budgets Component
![screenshot-localhost_3000-2019 10 21-10_06_10](https://user-images.githubusercontent.com/28536082/67187419-7148bd00-f3ea-11e9-9490-cf471e30be12.png)

### User
We propose to maintain the current workflow where we let the support button work the same as now:

- if you are logged in and verified, vote directly
- if you are not logged in, popup where to register / log yourself and return to the proposal. But with a new option in the popup: "Vote without registration", and make it very visible

Organizations that have activated the non-registered voting will have a dense popup. In order to improve the usability of the platform, it would be nice to have two versions of the current popup:

- When the unmatched voting functionality is not enabled, we would keep the current popup as it is now.
- When the unregistered voting functionality is activated, we would open a popup with a previous step where we would ask the user what he wants to do and presenting 2 buttons and the same form to login.

To participate you must validate yourself. How do you want to participate?
[I have no user and I do not want to]
[I already have a user, I want to make login]
[I have no user and I want to register]
Desktop Version
![screenshot-localhost_3000-2019 10 21-10_43_19](https://user-images.githubusercontent.com/28536082/67190085-a1df2580-f3ef-11e9-918c-5411ef751937.png)

Mobile Version
![screenshot-localhost_3000-2019 10 21-10_47_45](https://user-images.githubusercontent.com/28536082/67190431-3e092c80-f3f0-11e9-86c2-371ea1bb23b4.png)

If users, click "I have no user and I do not want to" it will be redirect to another page to check with the verification system in order to vote or give support.

![screenshot-localhost_3000-2019 10 21-12_13_49](https://user-images.githubusercontent.com/28536082/67197091-5e3ee880-f3fc-11e9-9c7b-7a79bb1171c6.png)

When the verification process has been completed successfully. The user is redirected to the page where he was and can take the action to vote.

## Tasks

- [ ] Add boolean "Enable voting targeting system without being registered" to Proposals Component
- [ ] Add boolean "Enable voting targeting system without being registered" to Budgets Component
- [ ] Modify modal when give vote/support
- [ ] Create page with the list of verifications.
- [ ] Redirect to the previous page, with a session of 30minutes and user can vote/give support to Proposals and Budgets Component.
